services:

  robot_framework_test:
    build:
      context: ./robot_framework_test
      dockerfile: Dockerfile
    container_name: robot_framework_test
    volumes:
      - ./robot_framework_test/output:/app/output
    stdin_open: true
    tty: true


  python_oop_and_testing:
    build:
      context: ./python_oop_and_testing
      dockerfile: Dockerfile
    container_name: python_oop_and_testing
    volumes:
      - ./python_oop_and_testing/output:/app/output
    stdin_open: true
    tty: true
